{
 "title": "Klevernator",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_epoch_number" }
   ]
  },
  {
   "title": "Total Validator Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_leader" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_is_syncing" }
   ]
  },
  {
   "title": "Synced Slots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_synchronized_slot{chainID=\"100007\",instance=\"localhost:8080\",job=\"Validator_Name_Here\"}"
    }
   ]
  },
  {
   "title": "Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_count_consensus_accepted_blocks"
    }
   ]
  },
  {
   "title": "Slots Per Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_slots_per_epoch{chainID=\"100007\",instance=\"localhost:8080\",job=\"Validator_Name_Here\"}"
    }
   ]
  },
  {
   "title": "Epoch Validator Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_num_validators{chainID=\"100007\",instance=\"localhost:8080\",job=\"Validator_Name_Here\"}"
    }
   ]
  },
  {
   "title": "Connected Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_connected_nodes{job=~\"Validator_Name_Here|server\"}"
    }
   ]
  },
  {
   "title": "Live Validator Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_live_validator_nodes{}" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_num_connected_peers{chainID=\"100007\",instance=\"localhost:8080\",job=\"Validator_Name_Here\"}"
    }
   ]
  },
  {
   "title": "Consensus Slot Time (Seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_slot_duration{chainID=\"100007\",instance=\"localhost:8080\",job=\"Validator_Name_Here\"}"
    }
   ]
  },
  {
   "title": "TPS Peak",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peak_tps{}" }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_mem_load_percent{}" }
   ]
  },
  {
   "title": "Current CPU %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_cpu_load_percent{}" }
   ]
  },
  {
   "title": "Transaction Pool Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "klv_tx_pool_load{}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "klv_mem_load_percent{chainID=\"100007\",instance=\"localhost:8080\",job=\"Validator_Name_Here\"}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_disk_written_bytes_total{device=\"sda\",instance=\"localhost:9100\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "klv_cpu_load_percent{chainID=\"100007\",instance=\"localhost:8080\"}"
    }
   ]
  }
 ]
}